In [ ]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# **Regression**

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Salary_Data.csv')
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [ ]:
df.dropna(inplace = True)

In [ ]:
x = df[['Age', 'Years of Experience']]
y = df.Salary

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2, random_state=5)

In [ ]:
scalar = StandardScaler()
xtrain_s = scalar.fit_transform(xtrain)

In [ ]:
smodel = Sequential([
    Input(shape = (2,)),
    Dense(4, activation= 'relu'),
    Dense(2, activation= 'relu'),
    Dense(1)
])

In [ ]:
smodel.compile(optimizer='sgd', loss='mae')

In [ ]:
history = smodel.fit(xtrain_s, ytrain, epochs= 70)

Epoch 1/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 113507.5078
Epoch 2/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 60062.4688
Epoch 3/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 58533.8750
Epoch 4/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 57928.8633
Epoch 5/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 59389.2617
Epoch 6/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55689.6484
Epoch 7/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 57728.6172
Epoch 8/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53342.0742
Epoch 9/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51025.4219
Epoch 10/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52207.2422
Epoch 11/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51410.5195
Epoch 12/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54943.8164
Epoch 13/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50445.5898
Epoch 14/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54797.5156
Epoch 15/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52327.6953
Epoch 16/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52521.9375
Epoch 17/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49380.9531
Epoch 18/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 48274.1289
Epoch 19/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50082.3477
Epoch 20/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52994.7812
Epoch 21/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51518.4961
Epoch 22/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 52680.8477
Epoch 23/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52773.7969
Epoch 24/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49146.3594
Epoch 25/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 46178.4961
Epoch 26/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51955.1914
Epoch 27/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48879.8828
Epoch 28/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51743.5117
Epoch 29/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 48778.7969
Epoch 30/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45643.2500
Epoch 31/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45674.1797
Epoch 32/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51491.5117
Epoch 33/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 47372.6602
Epoch 34/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 46266.5664
Epoch 35/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 43726.7969
Epoch 36/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49043.2656
Epoch 37/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 47177.8203
Epoch 38/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 44548.1562
Epoch 39/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 43653.3906
Epoch 40/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45725.0430
Epoch 41/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 44764.4258
Epoch 42/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 43035.5508
Epoch 43/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 44134.0312
Epoch 44/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 44580.5469
Epoch 45/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45526.8125
Epoch 46/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45608.7656
Epoch 47/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45563.6914
Epoch 48/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45826.8203
Epoch 49/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45535.2422
Epoch 50/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45838.1016
Epoch 51/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45764.6992
Epoch 52/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45482.1289
Epoch 53/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45369.7812
Epoch 54/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45199.8438
Epoch 55/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45528.1797
Epoch 56/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 45597.0195
Epoch 57/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45428.6562
Epoch 58/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45627.3242
Epoch 59/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 44881.2852
Epoch 60/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 45989.2734
Epoch 61/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 45347.8047
Epoch 62/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 45526.2656
Epoch 63/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 45468.5898
Epoch 64/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 45660.7656
Epoch 65/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 45974.5156
Epoch 66/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45623.4766
Epoch 67/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45457.8672
Epoch 68/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45607.8398
Epoch 69/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45488.6875
Epoch 70/70
168/168 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 46307.4336

In [ ]:
xtest_s = scalar.transform(xtest)

In [ ]:
loss = smodel.evaluate(xtest_s, ytest)
print(loss)

42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 47268.4844
46849.5078125

In [ ]:
# Predict
xnew = np.array([[46,10]])

In [ ]:
xnew_s = scalar.transform(xnew)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
sal_pred = smodel.predict(xnew_s)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step

In [ ]:
sal_pred

array([[112274.79]], dtype=float32)

# **Classification**

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Diabetes.csv')
df.head()

,Pragnency,Glucose,Blod Pressure,Skin Thikness,Insulin,BMI,DFP,Age,Diabetes
0,1,85,66,29,0,26.6,0.351,31,0
1,8,183,64,0,0,23.3,0.672,32,1
2,1,89,66,23,94,28.1,0.167,21,0
3,0,137,40,35,168,43.1,2.288,33,1
4,5,116,74,0,0,25.6,0.201,30,0

In [ ]:
df.dropna(inplace = True)

In [ ]:
x = df[['Age', 'Glucose']]
y = df.Diabetes

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2, random_state=5)

In [ ]:
scalar = StandardScaler()
xtrain_s = scalar.fit_transform(xtrain)

In [ ]:
cls_model = Sequential([
    Input(shape=(2,)),
    Dense(8, activation= 'relu'),
    Dense(4, activation = 'relu'),
    Dense(1, activation = 'sigmoid')
])

In [ ]:
cls_model.compile(optimizer='sgd', loss='binary_crossentropy', metrics= ['accuracy'])

In [ ]:
history = cls_model.fit(xtrain_s, ytrain, epochs= 70)

Epoch 1/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6491 - loss: 0.6840
Epoch 2/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6811 - loss: 0.6737
Epoch 3/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6502 - loss: 0.6693
Epoch 4/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6822 - loss: 0.6558
Epoch 5/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6590 - loss: 0.6538
Epoch 6/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6665 - loss: 0.6465
Epoch 7/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6469 - loss: 0.6409
Epoch 8/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6638 - loss: 0.6328
Epoch 9/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6862 - loss: 0.6118
Epoch 10/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6469 - loss: 0.6215
Epoch 11/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6346 - loss: 0.6201
Epoch 12/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6774 - loss: 0.5992
Epoch 13/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6794 - loss: 0.5932
Epoch 14/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6419 - loss: 0.6102
Epoch 15/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6571 - loss: 0.5890
Epoch 16/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6796 - loss: 0.5757
Epoch 17/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6812 - loss: 0.5788
Epoch 18/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6645 - loss: 0.5826
Epoch 19/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6681 - loss: 0.5685
Epoch 20/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6617 - loss: 0.5737
Epoch 21/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6778 - loss: 0.5610
Epoch 22/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6695 - loss: 0.5651
Epoch 23/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6771 - loss: 0.5570
Epoch 24/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6993 - loss: 0.5503
Epoch 25/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6917 - loss: 0.5509
Epoch 26/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6998 - loss: 0.5541
Epoch 27/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7006 - loss: 0.5468
Epoch 28/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7276 - loss: 0.5323
Epoch 29/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7076 - loss: 0.5375
Epoch 30/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7327 - loss: 0.5260
Epoch 31/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7326 - loss: 0.5322
Epoch 32/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7260 - loss: 0.5274
Epoch 33/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7279 - loss: 0.5240
Epoch 34/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7280 - loss: 0.5228
Epoch 35/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7534 - loss: 0.5209
Epoch 36/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7045 - loss: 0.5497
Epoch 37/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7226 - loss: 0.5256
Epoch 38/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7305 - loss: 0.5323
Epoch 39/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7349 - loss: 0.5287
Epoch 40/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7703 - loss: 0.5137
Epoch 41/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7605 - loss: 0.5154
Epoch 42/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7679 - loss: 0.5063
Epoch 43/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7690 - loss: 0.5030
Epoch 44/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7554 - loss: 0.5178
Epoch 45/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7685 - loss: 0.4941
Epoch 46/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7565 - loss: 0.5028
Epoch 47/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7771 - loss: 0.4929
Epoch 48/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7557 - loss: 0.5079
Epoch 49/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7466 - loss: 0.5011
Epoch 50/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7403 - loss: 0.5150
Epoch 51/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7604 - loss: 0.4913
Epoch 52/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7712 - loss: 0.4953
Epoch 53/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7509 - loss: 0.5022
Epoch 54/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7453 - loss: 0.5119
Epoch 55/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7810 - loss: 0.4704
Epoch 56/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7610 - loss: 0.4987
Epoch 57/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7499 - loss: 0.5027
Epoch 58/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7704 - loss: 0.4775
Epoch 59/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7352 - loss: 0.5212
Epoch 60/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7754 - loss: 0.4774
Epoch 61/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7760 - loss: 0.4769
Epoch 62/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7516 - loss: 0.5016
Epoch 63/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7800 - loss: 0.4720
Epoch 64/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7436 - loss: 0.5134
Epoch 65/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7439 - loss: 0.5171
Epoch 66/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7664 - loss: 0.4645
Epoch 67/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7512 - loss: 0.4896
Epoch 68/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7373 - loss: 0.5007
Epoch 69/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7529 - loss: 0.4922
Epoch 70/70
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7526 - loss: 0.4910

In [ ]:
# Evaluate
xtest_s = scalar.transform(xtest)

In [ ]:
loss = cls_model.evaluate(xtest_s, ytest)
print(loss)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7151 - loss: 0.5842
[0.5416383743286133, 0.7272727489471436]

In [ ]:
# Predict
xnew = np.array([[46,100]])

In [ ]:
xnew_s = scalar.transform(xnew)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
prediction = cls_model.predict(xnew_s)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

In [ ]:
prediction

array([[0.35280472]], dtype=float32)

In [ ]:
if (prediction < 0.5):
  result = ['negative']
else:
  result = ['positive']

In [ ]:
result

['negative']